<a href="https://colab.research.google.com/github/razibdeb/MachineLearning/blob/master/BMI_predector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

LOG_DIR = './log'
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
)
get_ipython().system_raw('./ngrok http 6006 &')

--2019-09-17 17:39:25--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 3.224.23.57, 3.227.43.216, 52.86.119.192, ...
Connecting to bin.equinox.io (bin.equinox.io)|3.224.23.57|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13607069 (13M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip’

ngrok-stable-linux- 100%[===================>]  12.98M  73.2MB/s    in 0.2s    

2019-09-17 17:39:26 (73.2 MB/s) - ‘ngrok-stable-linux-amd64.zip’ saved [13607069/13607069]

Archive:  ngrok-stable-linux-amd64.zip
  inflating: ngrok                   


In [0]:
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

https://eca09e2d.ngrok.io


In [0]:
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.utils import to_categorical
import math

from sklearn import preprocessing as pp


from random import seed
from random import randint
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from math import sqrt
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.


In [0]:
import numpy as np

LOW_BMI = 10.0
HIGH_BMI = 80.0

LOW_WEIGHT = 5.0
HIGH_WEIGHT = 80.0


LOW_HEIGHT = 75.0
HIGH_HEIGHT = 190.0

def getBMI(height, weight):
    return weight / ( (height/100) * (height/100) )


class Person :

    def __init__(self, name, age, height, weight):
        self.name = name
        self.age = age
        self.weight = weight
        self.height = height
        self.BMI = getBMI(height, weight)
        
    def printPerson(self):
        print("Name: " + self.name + " Age: " + repr(self.age) + " Height: " + repr(self.height) + " Weight: " + repr(self.weight) + " BMI:" + repr(self.BMI) )

    
              
def generatePersonArray(N):
    p_array = []
    random_age_array = np.random.randint(low = 1, high=120, size = N, dtype = 'int32')
    random_weight_array = np.random.randint(low = 1, high=120, size = N, dtype = 'int32')
    
    #for x in range(0,N)
    for age in random_age_array:
        
        heighest_weight = LOW_WEIGHT
        lowest_weight = HIGH_WEIGHT
        
        lowest_height = LOW_HEIGHT #cm
        heighest_height = HIGH_HEIGHT
        
        if(age < 5):
            heighest_weight = 10.0
            lowest_weight = 5.0
            lowest_height = 80.0
            heighest_height = 110.0
        elif(age < 10):
            heighest_weight = 20.0
            lowest_weight = 12.0
            lowest_height = 85.0
            heighest_height = 115.0
        elif(age < 20):
            heighest_weight = 40.0
            lowest_weight = 20.0
            lowest_height = 100.0
            heighest_height = 120.0
            
        elif(age < 30):
            heighest_weight = 50.0
            lowest_weight = 30.0
            lowest_height = 105.0
            heighest_height = 130.0
        else: #(age < 30)
            heighest_weight = 60.0
            lowest_weight = 50.0
            lowest_height = 115.0
            heighest_height = 135.0    
        
        random_height = np.random.randint(low = lowest_height, high=heighest_height, size = 1, dtype = 'int32')
        random_weight = np.random.randint(low = lowest_weight, high=heighest_weight, size = 1, dtype = 'int32')

        p1 = Person(name = "Razib", age = age, height = random_height[0], weight = random_weight[0])
        #p1.printPerson()
        p_array.append(p1)
    return p_array
        
        
def generateInputArray(p_array_train, t_data, t_label):
    
    for p in p_array_train:
        t_data.append([p.height, p.weight])
        #t_data.append(p.height)
        #t_data.append(p.weight)
  
        t_label.append(p.BMI)

        #BMI_array.append(p.BMI)
    
    
    
def sigmoid(x):
    #return 1 /(1+(math.e**-x))
    return (x - LOW_BMI) / HIGH_BMI
  
def reverse_sigmoid(y):
    return y* HIGH_BMI + LOW_BMI
  #return ln(y/(1-y))
  
  
def map_bmi(x):
    return (x - LOW_BMI) / HIGH_BMI
  
def reverse_bmi(y):
    return y* HIGH_BMI + LOW_BMI
  
def map_weight(x):
    return (x - LOW_WEIGHT) / HIGH_WEIGHT
  
def reverse_weight(y):
    return y* HIGH_WEIGHT + LOW_WEIGHT
  
  
def map_height(x):
    return (x - LOW_HEIGHT) / HIGH_HEIGHT
  
def reverse_height(y):
    return y* HIGH_HEIGHT + LOW_HEIGHT
########################





In [0]:
N_train = 1000


BMI_array = []

person_array_train = generatePersonArray(N_train)


training_data = []
training_label = []

generateInputArray(person_array_train, training_data, training_label)


print("Person Array Size: " + repr( len (person_array_train) ) )
print("Training Data Array Size: " + repr( len (training_data) ) )
print("Training Label Array Size: " + repr( len (training_label) ) )


print(repr(training_data[0]))
print(repr(training_label[0]))
print(repr(training_label[0]))

print(  training_data[0][1] / ( (training_data[0][0] * training_data[0][0]) / 10000 ) )

Person Array Size: 1000
Training Data Array Size: 1000
Training Label Array Size: 1000
[123, 57]
37.67598651596272
37.67598651596272
37.67598651596272


In [0]:
data_scaler = pp.MinMaxScaler(feature_range=(0,1))
print(data_scaler)
data_scaled = data_scaler.fit_transform(training_data)
print(data_scaled)

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.7962963  0.96296296]
 [0.77777778 0.83333333]
 [0.64814815 0.94444444]
 ...
 [0.74074074 1.        ]
 [0.64814815 0.96296296]
 [0.7037037  0.92592593]]


In [0]:

#
model = Sequential([
        LSTM(10, input_shape=(2, 1)),
        Dense(1)
        ])

model.summary()





Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 10)                480       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 491
Trainable params: 491
Non-trainable params: 0
_________________________________________________________________


In [0]:
#model.compile(Adam(lr=0.001), loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])
#model.compile(Adam(lr=0.001), loss = 'mean_squared_error', metrics=['accuracy'])
model.compile(loss='mean_squared_error', optimizer='adam')

In [0]:

print("Original Training Data")
print(training_data[0])

training_data = [[map_height(x), map_weight(y)] for x,y in training_data]

print("After Scalling Training Data")
print(training_data[0])

print("Reverse:")
#print(reverse_height(training_data[0][0]))
#print(reverse_weight(training_data[0][1]))


#td = np.array(training_data, dtype='float32')
#tl = np.array(training_label, dtype= 'bool')

#training_data = [[map_height(x), map_weight(y)] for x,y in training_data]
#training_data = array(training_data)
#training_data = training_data.reshape(10, 2, 1)


td = array(training_data)
td = td.reshape(1000, 2, 1)



print("BMI:")
#print(map_bmi(BMI_array[0]))
print("reverse BMI")
#print( reverse_bmi(map_bmi(BMI_array[0])))

#print(BMI_array)

tl_sigmoid = [map_bmi(x) for x in training_label]
#print(tl_sigmoid)

  
#for p in tl_sigmoid:
#  tl.append(p)


#print(tl_sigmoid[0])

#tl_sigmoid = np.array(tl_sigmoid, dtype = 'float64')





#print("NP Array BMI")
#print(tl[0])
print("Training array ")
print(td[0])

 


#print("Testing Array Size: " + repr( len (person_array_test) ) )
#print("Testing Data Array first: " + repr( len (testing_data) ) )
print("Testing Label Array Size: " + repr( len (tl_sigmoid) ) )

Original Training Data
[0.25263157894736843, 0.65]
After Scalling Training Data
[-0.39340720221606645, -0.05437499999999999]
Reverse:
BMI:
reverse BMI
Training array 
[[-0.3934072]
 [-0.054375 ]]
Testing Label Array Size: 1000


In [0]:
#tl
#tl = array(tl)
#tl = tl.reshape(1, 2, 1)

#training_data = [[map_height(x), map_weight(y)] for x,y in training_data]
#training_data = array(training_data)
#training_data = training_data.reshape(10, 2, 1)
training_data

array([[[0.27368421],
        [0.4625    ]],

       [[0.23684211],
        [0.575     ]],

       [[0.23684211],
        [0.65      ]],

       [[0.12105263],
        [0.0875    ]],

       [[0.29473684],
        [0.65      ]],

       [[0.28421053],
        [0.6       ]],

       [[0.26315789],
        [0.575     ]],

       [[0.24210526],
        [0.6       ]],

       [[0.27894737],
        [0.575     ]],

       [[0.22105263],
        [0.5875    ]]])

In [0]:
#def random_sum_pairs(n_examples, n_numbers, largest):
  
n_examples = 5
n_numbers = 2
largest = 10
X, y = list(), list()
for i in range(n_examples):
	in_pattern = [randint(1,largest) for _ in range(n_numbers)]
	out_pattern = sum(in_pattern)
	X.append(in_pattern)
	y.append(out_pattern)
# format as NumPy arrays
X,y = array(X), array(y)
# normalize
X = X.astype('float') / float(largest * n_numbers)
y = y.astype('float') / float(largest * n_numbers)
	#return X, y
 
#X = X.reshape(n_examples, n_numbers, 1)
X


array([[0.3 , 0.25],
       [0.45, 0.3 ],
       [0.4 , 0.05],
       [0.15, 0.4 ],
       [0.25, 0.2 ]])

In [0]:
td

array([[[0.25263158],
        [0.6375    ]],

       [[0.27894737],
        [0.625     ]],

       [[0.25789474],
        [0.65      ]],

       ...,

       [[0.25263158],
        [0.6125    ]],

       [[0.25263158],
        [0.575     ]],

       [[0.3       ],
        [0.65      ]]])

In [0]:



model.fit(td, tl_sigmoid, batch_size=1000, epochs=10)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
1000/1000 [==============================] - 1s 1ms/step - loss: 0.0942
Epoch 2/10
1000/1000 [==============================] - 0s 7us/step - loss: 0.0930
Epoch 3/10
1000/1000 [==============================] - 0s 7us/step - loss: 0.0917
Epoch 4/10
1000/1000 [==============================] - 0s 11us/step - loss: 0.0902
Epoch 5/10
1000/1000 [==============================] - 0s 11us/step - loss: 0.0888
Epoch 6/10
1000/1000 [==============================] - 0s 7us/step - loss: 0.0874
Epoch 7/10
1000/1000 [==============================] - 0s 6us/step - loss: 0.0859
Epoch 8/10
1000/1000 [==============================] - 0s 8us/step - loss: 0.0844
Epoch 9/10
1000/1000 [==============================] - 0s 7us/step - loss: 0.0830
Epoch 10/10
1000/1000 [==============================] - 0s 7us/step - loss: 0.0815


In [0]:
#print(td)
#td = array(td)
#print(td)
#print(tl_sigmoid[0])


#td = array(td)
#tl_sigmoid(tl_sigmoid)

In [0]:
sigmoid(99)

1.1125

In [0]:
test_d = np.array(testing_data, dtype='float32')
test_l = np.array(testing_label, dtype= 'bool')
print(test_d[0])
print(test_l[0])

[0.635      0.36666667]
True


In [0]:
N_test = 10
testing_data = []
testing_label = []
person_array_test = []


person_array_test = generatePersonArray(N_test)

generateInputArray(person_array_test, testing_data, testing_label)


testing_data = [[map_height(x), map_weight(y)] for x,y in testing_data]
testing_data = array(testing_data)
testing_data = testing_data.reshape(10, 2, 1)



print("Testing Array Size: " + repr( len (person_array_test) ) )
print("Testing Data Array Size: " + repr( len (testing_data) ) )
print("Testing Label Array Size: " + repr( len (testing_label) ) )


Testing Array Size: 10
Testing Data Array Size: 10
Testing Label Array Size: 10


In [0]:
testing_label

[32.64,
 32.0,
 35.45460008412956,
 28.6865234375,
 33.67530738507323,
 41.82983268066927,
 36.014405762304925,
 41.66372431325472,
 34.85367465897482,
 38.88888888888889]

In [0]:


loss = model.evaluate(testing_data,testing_label)


10/10 [==============================] - 0s 8ms/step


In [0]:
print(test_l)

[ True False  True  True  True  True  True False  True  True]


In [0]:
predict = model.predict(testing_data, batch_size=10, verbose=10)
for p in predict:
  print(reverse_bmi(p))

[22.53609]
[33.964256]
[33.859516]
[34.13349]
[33.28225]
[32.36001]
[26.998158]
[33.57557]
[33.785645]
[28.301908]


In [0]:
for p in testing_label:
  print(p)

10.569427929713305
33.48006696013392
30.30126449507604
30.4178145087236
41.58790170132326
37.15814506539834
21.43347050754458
38.83906503777982
30.769230769230766
27.434842249657063
